With version 3.0, the column 'ordr' is now 'position'

When generating a migration, ensure rename column is used, rather than drop / create column to preserve data.

    $this->renameColumn('tablename', 'ordr', 'position');
    
For multiple tables, this is handy

    <?php
    /**
     * This class has been auto-generated by the Doctrine ORM Framework
     */
    class Version1 extends Doctrine_Migration_Base
    {
      public function up()
      {
        $tables = array('table1', 'table2', 'table3', 'table4');
    
        foreach ($tables as $table)
        {
          $this->renameColumn($table, 'ordr', 'position');
        }
      }
    
      public function down()
      {
        $tables = array('table1', 'table2', 'table3', 'table4');
    
        foreach ($tables as $table)
        {
          $this->renameColumn($table, 'position', 'ordr');
        }
      }
    }